name: Pull-Request CI

on:
  pull_request:
    branches: [ release, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}
      - name: Use Node.js 12.16.2
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - run: npm install --legacy-peer-deps
      - run: npm run build:prepare
      - run: npm run test:ci
      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:cypress
