name: Pull-Request CI

on:
  pull_request:
    branches: [ release, develop ]
env:
  BEFORE_SHA: ${{ github.event.before }}
  TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install --legacy-peer-deps
      - name: Run Affected Lint
        shell: bash
        run: npm run affected:lint -- --base=origin/$TARGET_BRANCH
      - run: npm run build:prepare
      - run: npm run test:ci
      - name: Run Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          install-command: npm ci --legacy-peer-deps
          command: npm run test:cypress

  build_executables:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install --legacy-peer-deps
      - run: npm run build:prepare
      - run: npm run build:pkg -- -o release/out/memebox

      - run: release/out/memebox --cli-test-mode=true  --config=./release/config

      - run: npm run electron:build:only

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_output
          path: |
            release/out/
            release-electron/
            !release/config/**
            !release-electron/*-unpacked/**
            !release-electron/mac/**
